#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jan 24, 2019 05:10:49 AM PKT  platform: Linux
import sys
import os
from tkinter import messagebox
from datetime import  datetime
from sqlite3 import Error
import sqlite3
import Main

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

# import BillsViewer_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    # BillsViewer_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    # BillsViewer_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {DejaVu Sans} -size 30 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {DejaVu Sans Mono} -size 15 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1187x815+404+155")
        top.title("AF Softwares")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.025, rely=0.025, height=61, width=304)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(font=font10)
        self.Label1.configure(text='''Bills Viewer''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.025, rely=0.11, relheight=0.276, relwidth=0.375)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(width=445)

        self.i = tk.IntVar()
        self.DateRB = tk.Radiobutton(self.Frame1)
        self.DateRB.place(relx=0.697, rely=0.022, relheight=0.102
                , relwidth=0.231)
        self.DateRB.configure(activebackground="#f9f9f9")
        self.DateRB.configure(indicatoron="0")
        self.DateRB.configure(justify='left')
        self.DateRB.configure(text='''By Date''')
        self.DateRB.configure(value=1,variable = self.i)

        self.MonthRB = tk.Radiobutton(self.Frame1)
        self.MonthRB.place(relx=0.697, rely=0.422, relheight=0.102
                , relwidth=0.22)
        self.MonthRB.configure(activebackground="#f9f9f9")
        self.MonthRB.configure(indicatoron="0")
        self.MonthRB.configure(justify='left')
        self.MonthRB.configure(text='''By Month''')
        self.MonthRB.configure(value=2,variable = self.i)

        self.yearRB = tk.Radiobutton(self.Frame1)
        self.yearRB.place(relx=0.697, rely=0.289, relheight=0.102
                , relwidth=0.198)
        self.yearRB.configure(activebackground="#f9f9f9")
        self.yearRB.configure(indicatoron="0")
        self.yearRB.configure(justify='left')
        self.yearRB.configure(text='''By Year''')
        self.yearRB.configure(value=3,variable = self.i)

        self.WeekRB = tk.Radiobutton(self.Frame1)
        self.WeekRB.place(relx=0.697, rely=0.156, relheight=0.102, relwidth=0.22)

        self.WeekRB.configure(activebackground="#f9f9f9")
        self.WeekRB.configure(indicatoron="0")
        self.WeekRB.configure(justify='left')
        self.WeekRB.configure(text='''By Week''')
        self.WeekRB.configure(value=4,variable = self.i)

        self.TodayRB = tk.Radiobutton(self.Frame1)
        self.TodayRB.place(relx=0.697, rely=0.578, relheight=0.102
                , relwidth=0.204)
        self.TodayRB.configure(activebackground="#f9f9f9")
        self.TodayRB.configure(indicatoron="0")
        self.TodayRB.configure(justify='left')
        self.TodayRB.configure(text='''Today''')
        self.TodayRB.configure(value=5,variable = self.i)

        self.DateEntry = tk.Entry(self.Frame1)
        self.DateEntry.place(relx=0.258, rely=0.044,height=33, relwidth=0.126)
        self.DateEntry.configure(background="white")
        self.DateEntry.configure(font=font9)
        self.DateEntry.configure(selectbackground="#c4c4c4")


        self.MonthEnrty = tk.Entry(self.Frame1)
        self.MonthEnrty.place(relx=0.258, rely=0.267,height=33, relwidth=0.126)
        self.MonthEnrty.configure(background="white")
        self.MonthEnrty.configure(font=font9)
        self.MonthEnrty.configure(selectbackground="#c4c4c4")

        self.YearEntry = tk.Entry(self.Frame1)
        self.YearEntry.place(relx=0.258, rely=0.489,height=33, relwidth=0.126)
        self.YearEntry.configure(background="white")
        self.YearEntry.configure(font=font9)
        self.YearEntry.configure(selectbackground="#c4c4c4")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.09, rely=0.511, height=21, width=49)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''Year''')

        self.Label2_6 = tk.Label(self.Frame1)
        self.Label2_6.place(relx=0.09, rely=0.089, height=21, width=39)
        self.Label2_6.configure(activebackground="#f9f9f9")
        self.Label2_6.configure(text='''Date''')

        self.Label2_7 = tk.Label(self.Frame1)
        self.Label2_7.place(relx=0.067, rely=0.289, height=21, width=59)
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(text='''Month''')

        self.WeekEntry = tk.Entry(self.Frame1)
        self.WeekEntry.place(relx=0.528, rely=0.244,height=33, relwidth=0.126)
        self.WeekEntry.configure(background="white")
        self.WeekEntry.configure(font=font9)
        self.WeekEntry.configure(selectbackground="#c4c4c4")

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.393, rely=0.289, height=21, width=56)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''Week #''')

        self.TSeparator1 = ttk.Separator(self.Frame1)
        self.TSeparator1.place(relx=0.034, rely=0.733, relwidth=0.921)

        self.GetFilteredBillsButton = tk.Button(top)
        self.GetFilteredBillsButton.place(relx=0.076, rely=0.325, height=41
                , width=131)
        self.GetFilteredBillsButton.configure(activebackground="#f9f9f9")
        self.GetFilteredBillsButton.configure(text='''Get Bills''')
        self.GetFilteredBillsButton.configure(command = self.GetSummary)

        self.style.configure('Treeview.Heading',  font="TkDefaultFont")
        self.Scrolledtreeview1 = ScrolledTreeView(top, style="mystyle.Treeview", columns=('Name','Quantity', 'Price','Total'))
        self.Scrolledtreeview1.place(relx=0.025, rely=0.417, relheight=0.541
                , relwidth=0.952)


        self.Scrolledtreeview1.tag_configure('odd', background='#E8E8E8')
        self.Scrolledtreeview1.tag_configure('even', background='#DFDFDF')

        self.Scrolledtreeview1.heading('#0', text='item#')
        self.Scrolledtreeview1.heading('#1', text='Name')
        self.Scrolledtreeview1.heading('#2', text='Quantity')
        self.Scrolledtreeview1.heading('#3', text='price')
        self.Scrolledtreeview1.heading('#4', text='Total')
        self.Scrolledtreeview1.column('#0', width=50)  # , stretch=tk.YES
        self.Scrolledtreeview1.column('#1', width=400)  # , stretch=tk.YES
        self.Scrolledtreeview1.column('#2', width=100)  # , stretch=tk.YES
        self.Scrolledtreeview1.column('#3', width=100)  # , stretch=tk.YES
        self.Scrolledtreeview1.column('#4', width=100)  # , stretch=tk.YES
        self.tree_iterator = 0

        self.GetAllBillsButton = tk.Button(top)
        self.GetAllBillsButton.place(relx=0.227, rely=0.325, height=41
                , width=131)
        self.GetAllBillsButton.configure(activebackground="#f9f9f9")
        self.GetAllBillsButton.configure(text='''Get All Bills''')
        self.GetAllBillsButton.configure(command = self.GetAllBills)

        self.style.configure('mystyle.Treeview.Heading', font=('Calibri', 12))
        self.style.configure("mystyle.Treeview", highlightthickness=0, bd=0,
                             font=('Calibri', 15))  # Modify the font of the body

        self.AllBillsViewTreeView = ScrolledTreeView(top, style="mystyle.Treeview", columns=('date','Sale', 'Profit','Discount'))
        self.AllBillsViewTreeView.place(relx=0.413, rely=0.11, relheight=0.271
                                        , relwidth=0.564)

        self.AllBillsViewTreeView .tag_configure('odd', background='#E8E8E8')
        self.AllBillsViewTreeView .tag_configure('even', background='#DFDFDF')
        # self.tree = ttk.Treeview(self.parent, columns=('Dose', 'Modification date'))
        self.AllBillsViewTreeView .heading('#0', text='Bill #')
        self.AllBillsViewTreeView .heading('#1', text='Date')
        self.AllBillsViewTreeView .heading('#2', text='Sale')
        self.AllBillsViewTreeView .heading('#3', text='Profit')
        self.AllBillsViewTreeView .heading('#4', text='Discount')
        self.AllBillsViewTreeView .column('#0')  # , stretch=tk.YES
        self.AllBillsViewTreeView .column('#1')  # , stretch=tk.YES
        self.AllBillsViewTreeView .column('#2')  # , stretch=tk.YES
        self.AllBillsViewTreeView .column('#3')  # , st retch=tk.YES
        self.AllBillsViewTreeView .column('#4')  # , st retch=tk.YES
        self.AllBillsViewTreeView.bind("<Return>",self.open_this_bill)
        self.AllBillsViewTreeView.bind("<Delete>",self.Delete_the_bill)
        self.tree_iterator = 0

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

    def __del__(self):
        Main.LaunchWindow()

    def Delete_the_bill(self,event = None):
        curItem = self.AllBillsViewTreeView.focus()
        item = self.AllBillsViewTreeView.item(curItem, 'values')
        b_id = self.AllBillsViewTreeView.item(curItem, 'text')
        choice = messagebox.askyesno("confirmation", "Do you want to Delete this Bill?")
        choiceAddStockBack = messagebox.askyesno("confirmation", "Do you want to Add the Stock back?")
        if choice:
            global conn
            try:
                conn = sqlite3.connect("MyDataBase.db")
                c = conn.cursor()
                c.execute(f'DELETE FROM Bills WHERE Bill_Id = {b_id}')
                self.AllBillsViewTreeView.delete(curItem)
                if choiceAddStockBack:
                    c.execute(f'Select * from Sales WHERE billid = {b_id}')
                    rows = c.fetchall()
                    for row in rows:
                        c.execute(f'Update Stocks SET Profit = Profit - {row[5]}, Quantity = Quantity + {row[3]} WHERE Item_Id = {row[2]}')

                c.execute(f'DELETE FROM Sales WHERE Billid = {b_id}')
                conn.commit()



            except Error as e:
                print(e)

    def GetAllBills(self):
        global conn
        try:
            conn = sqlite3.connect("MyDataBase.db")
            c = conn.cursor()
            c.execute("SELECT * FROM Bills")
            rows= c.fetchall()
            for i in self.AllBillsViewTreeView.get_children():
                self.AllBillsViewTreeView.delete(i)
            for id, row in enumerate(rows):
                self.AllBillsViewTreeView.insert('', 'end', text=row[0],
                                              values=( row[1], row[3], row[2],row[4]))  #
                # Increment counter
                self.tree_iterator = self.tree_iterator + 1

        except Error as e:
            print(e)
    def open_this_bill(self,event = None):
        curItem = self.AllBillsViewTreeView.focus()
        item = self.AllBillsViewTreeView.item(curItem, 'text')
        global conn,c
        try:
            conn = sqlite3.connect("MyDataBase.db")
            c = conn.cursor()
            # print("comming")
            c.execute(f'SELECT Stocks.Name,Sales.Item_quantitty,Sales.Item_total,Sales.Item_price'
                      f' from Sales, Stocks'
                      f' WHERE Billid = {item} and Item_Id = Itemid')
            rows =c.fetchall()
            for i in self.Scrolledtreeview1.get_children():
                self.Scrolledtreeview1.delete(i)
            for id,row in enumerate(rows):

                self.Scrolledtreeview1.insert('', 'end', text=id,
                                                 values=(row[0], row[1], row[3],row[2]))  #
                # Increment counter
                self.tree_iterator = self.tree_iterator + 1

        except Error as e:
            print(e)

    def GetSummary(self, event=None):
        global conn, c
        try:
            sale = 0
            profit = 0
            conn = sqlite3.connect("MyDataBase.db")
            c = conn.cursor()
            day = self.DateEntry.get()
            month = self.MonthEnrty.get()
            year = self.YearEntry.get()
            e_date= year+'-'+month+'-'+day
            found = False

            if self.i.get() == 1:
                if len(day) ==0 or  len(month) == 0 or len(year) ==0 :
                    messagebox.showwarning("Invalid", "Please Fill All the fields")
                    return
                e_date = datetime.strptime(e_date, "%Y-%m-%d")
                c.execute(f'SELECT * from Bills where today_date = date("{e_date}")')
                rows = c.fetchall()
                for i in self.AllBillsViewTreeView.get_children():
                    self.AllBillsViewTreeView.delete(i)
                for row in rows:
                    print(row)
                    self.AllBillsViewTreeView.insert('', 'end', text=row[0],
                                                  values=(row[1], row[3],row[2]))  #
                    # Increment counter
                    self.tree_iterator = self.tree_iterator + 1
                    found = True

            elif self.i.get() == 2:
                if len(month)==0:
                    messagebox.showwarning("Invalid", "Please Fill the month field")
                    return
                if len(month)==1:

                    temp = "%-0"+month+"-%"
                else:
                    temp = "%-"+month+"-%"
                print(temp)
                c.execute(f'SELECT * from Bills where today_date like "{temp}"')
                rows = c.fetchall()
                for i in self.AllBillsViewTreeView.get_children():
                    self.AllBillsViewTreeView.delete(i)
                for row in rows:
                    print(row)
                    self.AllBillsViewTreeView.insert('', 'end', text=row[0],
                                                  values=(row[1], row[3],row[2]))  #
                    # Increment counter
                    self.tree_iterator = self.tree_iterator + 1
                    found = True

            elif self.i.get() == 3:
                if len(year)==0:
                    messagebox.showwarning("Invalid", "Please Fill the year field")
                    return

                temp = year+"-%"
                print(temp)
                c.execute(f'SELECT * from Bills where today_date like "{temp}"')
                rows = c.fetchall()
                for i in self.AllBillsViewTreeView.get_children():
                    self.AllBillsViewTreeView.delete(i)
                for row in rows:
                    print(row)
                    self.AllBillsViewTreeView.insert('', 'end', text=row[0],
                                                  values=(row[1], row[3],row[2]))  #
                    # Increment counter
                    self.tree_iterator = self.tree_iterator + 1
                    found = True
            elif self.i.get() == 4:
                day1 =0
                day2 =0
                if len(day) ==0 or  len(month) == 0 or len(year) ==0 :
                    messagebox.showwarning("Invalid", "Please Fill All the fields")
                    return
                week = self.WeekEntry.get()
                if len(week) == 0:
                    messagebox.showwarning("Invalid", "Please Fill the week field")
                    return

                if len(month)==1:
                    month = "0"+month

                if week == '1':
                    day1 = '1'
                    day2 = '8'
                elif week =='2':
                    day1 = '9'
                    day2 = '16'
                elif week =='3':
                    day1 = '17'
                    day2 = '24'
                elif week =='4':
                    day1 = '25'
                    day2 = '31'
                e_date1 = year + '-' + month + '-' + day1
                e_date2 = year + '-' + month + '-' + day2

                print(e_date1)
                print(e_date2)
                c.execute(f'SELECT * from Bills where today_date BETWEEN date("{e_date1}") AND date("{e_date2}")')
                rows = c.fetchall()
                for i in self.AllBillsViewTreeView.get_children():
                    self.AllBillsViewTreeView.delete(i)
                for row in rows:
                    print(row)
                    self.AllBillsViewTreeView.insert('', 'end', text=row[0],
                                                  values=(row[1], row[3],row[2]))  #
                    # Increment counter
                    self.tree_iterator = self.tree_iterator + 1
                    found = True

            else:
                messagebox.showwarning("Missing", "Please Select one option")


            if not found:
                messagebox.showinfo("Not Found", "No Record Found of this name")

            c.close()
            conn.close()
        except Error as e:
            print(e)
        finally:
            conn.close()




#The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()



def LaunchWindow():
    vp_start_gui()




